### ISSUE TITLE
Bug in "Bugs" section

### ISSUE THREAD

**Issue by maximumplank** [BTCfork/BTC-Forks-Roadmap#33]
Small typo in 8.iii. Bugs, currently reads:
"Obviously every effort will be put towards making sure any software that is released for use but every software..."

Seems like you want to say something about releasing robust, bug free software, just need to add a few words. I also take slight issue with the use of "obviously." Releasing bug-free software is a laudable goal, but should never be taken for granted. Perhaps something like:
"Every effort will be put towards making sure any software that is released for use is robust and free from issues, but all software runs the risk of having bugs in the code. Bugs could range anywhere from minor to major. We will use Github's issue tracker or a similar service to report bugs and discuss fixes in an attempt to streamline the debugging process."

**Comment by Solon-Archon** [comment]
Thanks for the input. Much prefer your text.
